### PR TITLE
Fix update dependencies from staging pipeline command for SDK-only releases

### LINKED ISSUE #6085: Update-dependencies-internal pipeline cannot handle SDK-only releases
Related: https://github.com/dotnet/dotnet-docker-internal/issues/5952 [internal link]

The pre-release validation update pipeline runs into an issue with SDK-only releases. Here's what happens:

Let's say we release version 8.0.200, and we follow that up with an SDK-only release of 8.0.201. If we want to test 8.0.201 then we would call the update-dependencies tool would be called with the arguments:

```
Set-DotNetVersions \
-ProductVersion 8.0 \
-RuntimeVersion 8.0.X \
-AspnetVersion 8.0.X \
-SdkVersion 8.0.201 \
-UseInternalBuild $true \
...
```

This will cause the SDK pipeline to look for shas from the SDK build staging pipeline given by the argument `--internal-base-url=$InternalBaseUrl`. Since that build was SDK-only, the pipeline will fail to find any SHAs for the pre-existing ASP.NET and Runtime versions. This causes the pipeline to fail.

The workaround is currently to update dotnet versions manually and push a branch yourself.

For an easy solution, we could potentially add a pipeline parameter for "Is SDK-only release".

### PR DESCRIPTION
**Pull request by lbussell**
Fixes #6085, #6817

### CODE REVIEW

File: eng/update-dependencies/FromStagingPipelineCommand.cs [hunk 1]
```diff
@@ -146,14 +146,18 @@ public override async Task<int> ExecuteAsync(FromStagingPipelineOptions options)
             return exitCode;
         }
 
-        var commitMessage = $"Update .NET {majorMinorVersionString} to {productVersions["sdk"]} SDK / {productVersions["runtime"]} Runtime";
+        var commitMessage = releaseConfig switch
+        {
+            { SdkOnly: true } => $"Update .NET {majorMinorVersionString} SDK to {productVersions["sdk"]}",
```
Comment (MichaelSimons) [inline eng/update-dependencies/FromStagingPipelineCommand.cs:151]: Nit: consider a pattern where "Update .NET {majorMinorVersionString} SDK to {productVersions["sdk"]}" is not duplicated.  Benefit increased readability and maintainability.
